### ISSUE TITLE
Do you plan to release the model?

### ISSUE THREAD

**Issue by jcuenod** [clemeth/tagparse#1]

**Comment by clemeth** [comment]
Thanks for asking.

I could do that, but it would depend on what model you are looking for. I've trained too many for it to be practical to release them all. Keep in mind that you can use this repo to train models on any dataset (in any language). If you want one for Ancient Greek, it would probably make most sense to go for a joint model trained on the [UD version of PROIEL](https://github.com/UniversalDependencies/UD_Ancient_Greek-PROIEL), as it is the best performing overall with the most consistent annotation scheme. I don't have such a model on drive right now, though.

Do you mind if I ask what you want to do with it? So far, I haven't used these models for anything non-experimental, so if you're looking to do something specific it might be good to know if a new one has to be trained either way.

Of course, if you're able, training a model yourself is also a possibility.

**Comment by jcuenod** [comment]
Thanks, I'm wanting to tag the Apostolic Fathers (see https://github.com/jtauber/apostolic-fathers). If you have a model that will work well on that dataset, let me know. I'll give training a go, but I don't have good access to training compute.

**Comment by clemeth** [comment]
I've uploaded a joint model trained on the UD version of PROIEL to [Hugging Face](https://huggingface.co/clemeth/ancient-greek-bert-finetuned-proiel-tag-parse): `clemeth/ancient-greek-bert-finetuned-proiel-tag-parse`.

I haven't written a prediction script, but you should be able to modify [`test.py`](https://github.com/clemeth/tagparse/blob/9be9ca8/test.py) into one quite easily; just leave out all the parts doing evaluation and make it load a HuggingFace model instead of a local path. You'd also need to write your own way of batching the data unless you convert it all to CoNLL-U first. If you do that I think it should work out of the box, so maybe that's the best choice.

Let me know if you have any questions.

**Comment by jcuenod** [comment]
Thank you, that's great! I've got it working.
